/**
 * 遊戲參數
 * PLAYER_BET：單次下注金額
 * ANY_NUMBER：可任意搭配號碼
 * SPECIAL_NUMBER：特別號碼
 * REEL_HIGH_RANGE：高賠率範圍
 * REEL_LOW_RANGE：低賠率範：
 */
exports.PLAYER_BET = 88;
exports.ANY_NUMBER = 50;
exports.SPECIAL_NUMBER = 20;
exports.TEST_BASE_GAME_JSON;
exports.TEST_BOUNS_GAME_JSON;
exports.REEL_HIGH_RANGE = 1000;
exports.REEL_LOW_RANGE = 100;

/**
 * 測試參數
 * BASE_GAME_CHECK_RUN_TIMES：RTP測試次數
 * REEL_JSON_RTP_TEST_RUN_TIMES：RTP2次測試次數
 */
exports.BASE_GAME_CHECK_RUN_TIMES = 1000 * 1000;
exports.REEL_JSON_RTP_TEST_RUN_TIMES = 10 * 1000 * 1000;

/**
 * 功能開關
 * FREE_GAME_CHECK_SWITCH：freeGame測試開關
 * BASE_GAME_CHECK_INSERT_ALL_REEL_NUM_SWITCH：將所有測試過的 Reel 組合寫入 JSON 檔開關
 * BASE_GAME_CHECK_INSERT_HIGH_RANG_REEL_NUM_SWITCH：將高賠率的 Reel 組合寫入 JSON 檔開關
 * BASE_GAME_CHECK_INSERT_NOMAL_RANG_REEL_NUM_SWITCH：將一般賠率的 Reel 組合寫入 JSON 檔開關
 * BASE_GAME_CHECK_INSERT_LOW_RANG_REEL_NUM_SWITCH：將低賠率的 Reel 組合寫入 JSON 檔開關
 * BASE_GAME_CHECK_APPEND_FILE_SWITCH：輸出測試文件開關
 */
exports.FREE_GAME_CHECK_SWITCH = true;
exports.BASE_GAME_CHECK_INSERT_ALL_REEL_NUM_SWITCH = false;
exports.BASE_GAME_CHECK_INSERT_HIGH_RANG_REEL_NUM_SWITCH = false;
exports.BASE_GAME_CHECK_INSERT_NOMAL_RANG_REEL_NUM_SWITCH = false;
exports.BASE_GAME_CHECK_INSERT_LOW_RANG_REEL_NUM_SWITCH = false;
exports.BASE_GAME_CHECK_APPEND_FILE_SWITCH = false;
